server:
  private-key: ""
  version: "1.0"
  name: go-mcp-demo
  log-level: "INFO" # OPTIONS: TRACE, DEBUG, INFO(default), NOTICE, WARN, ERROR, FATAL

ollama:
  base_url: "http://127.0.0.1:11434"
  model: "qwen3:1.7b"
  options:
    request_timeout: "30s"
    keep_alive: "5m"
    temperature: 0.2
    top_p: 0.9
    top_k: 40
    max_tokens: 1024
    extra: { }  # 可选，原样透传到 options

cli:
  system_prompt: "你是一个可以调用外部工具(MCP)的助手，请在需要时调用合适的工具。"
  history: true
  max_turns: 8

mcp:
  server_name: "stdio.mcp.demo"
  transport: "stdio"
  stdio:
    server_cmd: "./bin/mcp-server" # 如果是windows，需要改成 ./bin/mcp-server.exe
    server_args: []



services:
  host:
    name: host
    load-balance: false
    addr:
      - 127.0.0.1:10001
  mcp_server:
    name: mcp-server
    load-balance: false
    addr:
      - 127.0.0.1:10002